Cherry-pick our workaround patches
AbletonAppDev/cucumber-cpp pull request #3
Opened 2017-08-16 09:39 UTC by nre-ableton

This PR basically just brings the `ableton-master` to the same point as the old `nre_master_ableton-octo` branch (which lives on under the tag name `ableton-initial-migration`). The only difference is that I've cleaned up the commit messages a bit.

ping @ala-ableton

2017-08-16 13:00 UTC, ala-ableton reviewed
I only reviewed the first commit yet.

2017-08-16 13:00 UTC, ala-ableton commented on CMakeLists.txt
> +set(CUKE_ENABLE_SHARED_LIB OFF CACHE BOOL "Generate a shared library")
I don't think we need to change the `CMakeLists.txt` in this commit.

2017-08-16 13:00 UTC, ala-ableton commented on include/cucumber-cpp/internal/CukeEngineImpl.hpp
> +class CUKE_API_ CukeEngineImpl : public CukeEngine {
Missing `#include "CukeDll.hpp"`

2017-08-16 13:00 UTC, ala-ableton commented on src/CMakeLists.txt
> +add_library(cucumber-cpp ${CUKE_LINKAGE} ${CUKE_SOURCES} main.cpp)
Same thing here, I don't think we should change the `CMakeLists.txt` files in this commit.

2017-08-16 13:42 UTC, ala-ableton requested changes
The title of the second commit should start with a verb.

2017-08-16 13:42 UTC, ala-ableton commented on src/HookRegistrar.cpp
> -
Removing this line doesn't seem necessary.

2017-08-16 13:42 UTC, ala-ableton commented on src/Regex.cpp
> +#include <cucumber-cpp/internal/hook/HookRegistrar.hpp>
Please sort alphabetically.

2017-08-16 13:42 UTC, ala-ableton commented on src/Regex.cpp
> +                   && HookRegistrar().execStepMatchingHook(matchResults);
Why not indent with only one level of indentation?

2017-08-24 13:22 UTC, nre-ableton commented on CMakeLists.txt
> +set(CUKE_ENABLE_SHARED_LIB OFF CACHE BOOL "Generate a shared library")
True, fixed

2017-08-24 13:23 UTC, nre-ableton commented on include/cucumber-cpp/internal/CukeEngineImpl.hpp
> +class CUKE_API_ CukeEngineImpl : public CukeEngine {
Fixed

2017-08-24 13:24 UTC, nre-ableton commented on src/CMakeLists.txt
> +add_library(cucumber-cpp ${CUKE_LINKAGE} ${CUKE_SOURCES} main.cpp)
Fixed

2019-04-25 15:04 UTC, closed without merging